# Generated by Django 6.1 on 2026-09-08 02:06

import accounts.validators
import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_customuser_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='profile_picture',
            field=cloudinary.models.CloudinaryField(blank=True, help_text='JPEG/PNG/WebP, up to 5MB.', max_length=255, null=True, validators=[accounts.validators.validate_image_file_size], verbose_name='profile_picture'),
        ),
    ]
