# Generated by Django 6.1 on 2026-09-08 04:49

import accounts.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_customuser_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='profile_picture',
            field=models.ImageField(blank=True, help_text='JPEG/PNG/WebP, up to 5MB. Auto-resized to 512px.', null=True, upload_to=accounts.validators.ProfilePictureUploadPath(), validators=[accounts.validators.validate_image_file_size]),
        ),
    ]
