# Generated by Django 6.1 on 2026-08-17 04:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0001_initial'),
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='semester',
            field=models.ForeignKey(blank=True, help_text='Leave blank for a free exam.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='exams', to='payments.semester'),
        ),
    ]
